name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment-target:
        description: "Choose target"
        required: true
        default: "first_test"
        type: choice
        options:
          - first_test
          - second_test
          - third_test
          - all_tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: First Test
        if: ${{ github.event.inputs.deployment-target == 'first_test' }}
        run: pytest test_this.py::test_one
      - name: Second Test
        if: ${{ github.event.inputs.deployment-target == 'second_test' }}
        run: pytest test_this.py::test_two
      - name: Third Test
        if: ${{ github.event.inputs.deployment-target == 'third_test' }}
        run: pytest test_this.py::test_three
      - name: All Tests
        if: ${{ github.event.inputs.deployment-target == 'all_tests' }}
        run: pytest
