name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment-target:
        description: "Choose target"
        required: true
        default: "simple_button"
        type: choice
        options:
          - simple_button
          - like_a_button
          - all_tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Simple Button
        if: ${{ github.event.inputs.deployment-target == 'simple_button' }}
        run: pytest tests/test_simple_button.py
      - name: Like a Button
        if: ${{ github.event.inputs.deployment-target == 'like_a_button' }}
        run: pytest tests/test_like_a_button.py
      - name: All Tests
        if: ${{ github.event.inputs.deployment-target == 'all_tests' }}
        run: pytest
